[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "5797e50528bf28f8f622f6a6d57ce14b1d8da581"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "203ab6cf280b869f9db5f6addaa1980da1d6a778254839cebc453247bc0348ea"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.aarch64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "2690173af35d9d273b493c02f76e2e05373af7a8"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "8357331d93b99ea5f7d76a4ecd83db805755600aaa016f1b41a09771bdf4f32e"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.aarch64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "3ceddd9a4ab88829a5e65fd875133b645cdd1618"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "9240c1d121422ab3766d7f50df317dc7f7535ab99742610e459f0af4979e29ae"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.aarch64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "f9532965a7c874bbbeec08093cc8c4da5367efe8"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "6a4b728f6de870d6a2b20d3cea49e915264b824d47a7e23655ea419830806934"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.aarch64-unknown-freebsd.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "13ec22e97fc195d62ef09e71ac64f1e9f42ed694"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "531ad1e2840451959b147dc476a325c9e06598ce951fd8bfc2c801ec766dc591"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.armv6l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c60aee39d61a225edffaabd7b854407ccb50bf50"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "e02853a77f8fe9fac3d441be833835e620c1db7bc47a3f4c2217a3713ac89906"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.armv6l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32556ff2e44120038d7e29d20339cff955a3088a"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "4a33bcae5e9b19261171e761a9e6bf9b4c796ffc2e6401821338e2dfeb0f1113"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.armv7l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1956dfba219144313c9c0336552a2851120c2ff"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "711c34fd5ada5489c221758baea53dad16953bf812985d03efa5cb5ddb652397"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.armv7l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "9b2fdaf7dc4c24f2afd601580bf9c02bc54f7c20"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "9505296b506fa716a8897a24be73f5e2d1e198c91dc3e0045fb59fd527c128eb"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.i686-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "e13515d1e6ee1d82a7d0a4fd1afc44706bd651ed"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "bad501a6fb4827d655bfa461c3fc5fa4b74559b9b05259d4e1c5dd1449e6c3d8"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.i686-linux-musl.tar.gz"
[[libwebsockets]]
arch = "powerpc64le"
git-tree-sha1 = "26ac30f64d0c0443089b1516044bf0633f36b822"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "c13c24c25d3bc8f19dc1ab7559f04f1e4da4cc03b4070b1f5c18f15298015079"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.powerpc64le-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "riscv64"
git-tree-sha1 = "4425ae7ca495ccaa444f69b259dbc9a9613a4577"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "46a5332621711a271a86b530ce13e8af2de228519f114dd9d14ba9a179e0231d"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.riscv64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "fa960048c6a9c70b1dc5ea420d34ec29aefb8b88"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "14d5f2e7f687ee664e93e9775078b36944f63dd5d7cf90ca936ecb51f7699fc1"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.x86_64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "9fb764b2fbc44a1e320f4af6cc206a6d6f8e73f4"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "14469dd1ba06468c514aa435cba5f233fb6f1abc0e4a628e2cdf2b4ddd3fd2af"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.x86_64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "64a866927401dc0027cae4dd83b54399d31b8642"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "4cfa2bfed1a01687986eba89d3b211b614cea8b56b59a9361ad1eab1eea5c46f"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.x86_64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "6b61c8b311a0dfcd3ed0dcbab78e2482016ca4b3"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "6dceab8c118b3504d034b3c35784067fa8977aa92f52f9480ed2891cb9fed895"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+1/libwebsockets.v4.4.0.x86_64-unknown-freebsd.tar.gz"
