[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "187a8618e840ab9f390eb439682ba3b581b0db45"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "1678c7e234634b667bc2ff68e94e60c01f974da4ee3488ae16f227b1be97ac8d"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.aarch64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "ad9d44d38f881fbdfb8cfc9d48cad2c47c44fe30"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "f7e99d04ff4a10b909a8377fc7a9113673a9e0b1ec0537753c15b16b8f45f53e"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.aarch64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "485083af79e64676182c697a427c7b94f1a5556f"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "bbb5b773368d4a24dceb820784b042df4fca30b5e88423e356ad0a6950e276b7"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.aarch64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "7a74863bca4c222955072ef24d633e2ede8ebcd6"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "adb88514c55214dce6963e696ec54ee00155acb2d8346947e8dbced3e6946c4a"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.aarch64-unknown-freebsd.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5cd289378ca3f891b527de2882e1315528041cc0"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "5085e0c5ed9ca479f766f03b59975d667dfdd820a5b8335f10e433b0ccd4dfad"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.armv6l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7c050a43e8001233f791bc86da5b01a773820d3"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "1c05e0c39164218e5cd70f69435c3dbf1b0017840576e0d546e1e9082a6909ef"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.armv6l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61ec1833781a99d70bb1f5a316bf62fe007b0ff9"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "831f3382f340e2a15adf8fe96d58a5bc7301f3730adbb35d02820d6c47fe7857"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.armv7l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "49ee57f1646cb81a2c8377bae3fefda272611ec9"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "834f78d9f6771ddc6c4776bc04545793e43cc63faadb07be1ad6e2d7cdf9a660"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.armv7l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "bcc6786019fce26fe9892edc450d3eece73e67c6"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "491b6e57c967abc10cfae70564c8ed974cb3de20672e5c7bf1602a645d3fd868"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.i686-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "7858eed5f184fc00e2ef1a1773a0a9ea8f7c9bd6"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "deaab02d2cdad7c0dfbb5127c57cfce7a54faa8de3314fa4fd43d095d47cb79d"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.i686-linux-musl.tar.gz"
[[libwebsockets]]
arch = "powerpc64le"
git-tree-sha1 = "bc2d2ce5d95d44f65420bf20365d6840c9a4dcde"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "09e97c9e7a6a0f3695af90cf80292f3cb8ddf6765f5e4581914618b17fd6b4b6"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.powerpc64le-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "riscv64"
git-tree-sha1 = "d571715e1372b18052b5323df9dbcf66dd71aaf8"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "c3403f4a2af3b9aa2f58e52a219837fc52f004adb2ce8725a2f6e065e86e7db9"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.riscv64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "301ff2fa5f39bb3423e2536c930d4493690fe7b9"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "10a82cc128e529f8691906c3f8a594cc7df8af781715b4d3b12ddc8492585f5f"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.x86_64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "a43b6728fe1c4aaf74583faad86a39165323ff5d"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "2d8fc20fbbcb92c51c17f1e7dbcd384d72a94dbf7860ffbb6e91b584ee4aeee8"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.x86_64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "3668b506bd693c14222304ccb3153e385172c827"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "89f88c664fdeda4e3adec028242637bd82100fe3c06e41365e8ec78b8f6efc75"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.x86_64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "50b0eadb58ba1f950edf234944937f5c909041bd"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "513a7902f77adb131b44cf34e783afc00a4fad9ac7ce263461eadf2faf2056d4"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.4+0/libwebsockets.v4.3.4.x86_64-unknown-freebsd.tar.gz"
