[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "4a742086966d6a750cbce0b4d0603be04b5d4b71"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "e210719c829bad35adfcdf08372ebad3ad8b5aaa9ef2a00c3f814887b150dd0b"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.aarch64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "ac0bea41300c321112d60af01461de9f83c2049d"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "958174bc373ca1582f5ba49fb5181b2bd33443e815d02a513cda9992b7efe43a"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.aarch64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "7a967e8c23370a706f08cc974e98f19da94d3d66"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "dc7f3f61db72f76b8e4845862d00a9b4860724b365a0fbf0ac24eea18aca2c00"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.aarch64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "e64c7d00799aabe15817fd97053368790c08a192"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "c3ae14bbec2f337fc0cd355e20d9d28c034b8025deb9e0f92a05ff02de9f9847"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.aarch64-unknown-freebsd.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e46589abcce9502eec18c8250667ae734daec76"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "4fbe6138e8d05d2f53bb32d37c167568bac34b3313f1fdb9215739f9ea296583"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.armv6l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6eb859b689b96929570a27fcc0037c144675c864"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "adb0396cba6ebef289e3bd640ce9a4cac45d04521dc3b2ea840342b5dc6b09dd"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.armv6l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9921733ff0ab31ad66a2d343b4e76563c3bdd8bb"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "5ffab1a1bb0f3e09fc9b9652ca24c45d1fe67e8e715c91df2833b37aa8e2d9d7"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.armv7l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8a30c6e76a521dc5099138898228e579076df81"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "9f170c7776a21d412d524dcb970c909bf2f3450c6d6f5c701e76a67a07516995"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.armv7l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "b60907d4b3420f4d15722f3d68969d214b766c8e"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "5f01508674c624ff5c6cd5672d10f8a0484b7fa0989df73d166a13aa5b077905"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.i686-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "213e6b2f13a5e8b89123cba495d3db4c63e698dd"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "62132a079b518fc30156e7e6ae73e9a0eb48db49517af63594bce3ae5688f7e4"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.i686-linux-musl.tar.gz"
[[libwebsockets]]
arch = "powerpc64le"
git-tree-sha1 = "7f54ca762436b150ba46baea64595ddc21712568"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "9d3527603ec4d7fcf5de3adad200eff4e18f236f1c8305848baac948881523b1"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.powerpc64le-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "riscv64"
git-tree-sha1 = "41db99a297a1ff418375226b2017e86deaee372f"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "c7c2b2d0c63c191e6a635d39eecc6539eaa75759eedc0e1148483ef9c59bd3e9"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.riscv64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "a4ce0ef8634a0ae2ff2b8302d72f16bb1ec80dfa"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "496fed8af500af4e22bd5bf52125dcc76dfd944a9eaede99f26a48a57d607de2"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.x86_64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "e7ec14460565dfa00dc8eb2c9c5bdc2cf9e2c70e"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "64dc269dd0db22c898e0c5a9bbc012e0be33d38ea1d95e1279dc460ddf9de6f0"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.x86_64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "996349a293e16200c32b5090a734d6bdf4d6cfc6"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "a8eb6419233f2256758b0e69baf52b6eafc3f687309fa7a518ba2aed7c9517a0"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.x86_64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "d4e158fa89c462ed2b39211c6fbb1a78e158e819"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "18acc64712a02e25d9358a730613ffd1bc79b3e89a9abf85e781206c71e46766"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.4.0+0/libwebsockets.v4.4.0.x86_64-unknown-freebsd.tar.gz"
