[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "95f53a8eb49bf01af715aec2aff3aeea02863bf8"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "68dddc01f4e374b649dea89206c2407a24db1b0a130226f262f5879719fa13d3"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.aarch64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "9b3c13d009a29b9b1a370a04c91a7935d42f517c"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "b5a1c23403fc81bda01d9fcdad9bd3a8e94f1a040674e7e311f7d9bb90cb839b"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.aarch64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "21267cb42dfa1bf348a6e979f89594c85a05b83a"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "b92e722ace772a4647970e9245f66c4070072de8de5c3842c2cdba8a3bdd683d"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.aarch64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "aarch64"
git-tree-sha1 = "61485ae366ef2a76bb283e8eb4e651debefe87d6"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "f4338083bdc28cc7b4c13c541505673a2cfd8a8e6c086c9cd14a920621178874"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.aarch64-unknown-freebsd.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b08c709d4cec1ed5cdb9b32c1a950c851c79eedd"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "1fe12206fcfbb635c079093a8fb5cacdbd03626ef114b55eb4936c41e3117fbf"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.armv6l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "62ea2775478381aef449065b95570cbcf0abb1f8"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "f03fd5c27280edb1c7ef90b51a19862c4d61e78759907f6905eafd8f4bb047d4"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.armv6l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc94b40c1d4e232d40c847813e3df225fecbe820"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "cc5c29d9c08f81bfc6160c9db9d205da5389b2a48d6abe87abb6bea6aa20ebc4"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.armv7l-linux-gnueabihf.tar.gz"
[[libwebsockets]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ec5a4af0425fc96c8b86e87ed0d7b1106db604a"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "c7b4282119b1a853dd7d2b0fcf7ad0560af866add0a45b736979c55ae9ae1b96"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.armv7l-linux-musleabihf.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "032a3ff56de1a197cd579915e66c7550c8726485"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "faf4f75d9b778097736980495c8bc3401b59d8a913b94db26442df52378c5f9d"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.i686-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "i686"
git-tree-sha1 = "92207e849d5df287f94d666c793764ba9ee85fe8"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "d9969a91b84cac7f1efaaec83d5b4dcb9caf9ac5b221f71af1b5a71a6fc6333f"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.i686-linux-musl.tar.gz"
[[libwebsockets]]
arch = "powerpc64le"
git-tree-sha1 = "d08215851a603c37fa05eff266d5924e7e9afac4"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "141cbe1c0e2707e7a868098990f8b42f28b0042466fb89a48179203663640b97"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.powerpc64le-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "a26c0851c34b0fcc093ca94cc9c39629373b5091"
os = "macos"

    [[libwebsockets.download]]
    sha256 = "3184e021569187355e84c1a461489a76f90fac1039f826fb9fb77408078f7c3d"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.x86_64-apple-darwin.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "95ced4f46933bfca7ea6ee8affb3d6790faaa524"
libc = "glibc"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "e72bfb033630b76a988e1b529cb1b53197a511f314a62246363d77801dd16db5"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.x86_64-linux-gnu.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "7142755f0ace5c5fb46df1af9e848ca677bb4205"
libc = "musl"
os = "linux"

    [[libwebsockets.download]]
    sha256 = "2386e844d7a8b03f14760c3fdc63b1a903d3dbab402dc1b3827d6ddf199f515b"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.x86_64-linux-musl.tar.gz"
[[libwebsockets]]
arch = "x86_64"
git-tree-sha1 = "8ff85979001d277dd62d6f05040a71b479d498b9"
os = "freebsd"

    [[libwebsockets.download]]
    sha256 = "fddbd33620aa4fca4e07c648224320f438894cc647c8b43b952d1abd30eebf82"
    url = "https://github.com/JuliaBinaryWrappers/libwebsockets_jll.jl/releases/download/libwebsockets-v4.3.3+0/libwebsockets.v4.3.3.x86_64-unknown-freebsd.tar.gz"
